POST http://localhost:4000/notes/create
content-type: application/json

{
    "name": "Nota 9",
    "description": "description 9",
    "tags": ["art", "post", "Dbug", "restauration"],
    "imgUrl": ""
    
}